### ISSUE TITLE
HER tutorial notebook not loading

### ISSUE THREAD

**Issue by moshebeutel** [Stable-Baselines-Team/rl-colab-notebooks#1]
Hi
While trying to load HER tutorial notebook I get the following error:

Notebook loading error
There was an error loading this notebook. Ensure that the file is accessible and try again.

JSON.parse: unexpected character at line 75 column 7 of the JSON data
https://github.com/Stable-Baselines-Team/rl-colab-notebooks/blob/master/stable_baselines_her.ipynb

JSON.parse: unexpected character at line 75 column 7 of the JSON data
wba/<@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200410-085600-RC00_305864463:1502:377
Ga@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200410-085600-RC00_305864463:17:336
Ea.prototype.next_@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200410-085600-RC00_305864463:15:474
Ia/this.next@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200410-085600-RC00_305864463:18:206
b@https://colab.research.google.com/v2/external/external_polymer_binary.js?vrz=colab-20200410-085600-RC00_305864463:26:268

Great tutorials and rl library btw :)

Moshe

**Comment by araffin** [comment]
Hello,
Thanks for reporting the issue, should be fixed now.

**Comment by araffin** [comment]
Fixed in 0060e60c63ac99a1a18a85

**Comment by moshebeutel** [comment]
It is.thanks
