### ISSUE TITLE
ImportError in colab notebook

### ISSUE THREAD

**Issue by amrzv** [Stable-Baselines-Team/rl-colab-notebooks#11]
Hi.
When running `1_getting_started.ipynb` notebook in colab there raises an `ImportError` during `record_video` call:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/36787333/212548189-00235772-9d2a-4970-822a-c5b87e2579be.png">

However,  after installing `pyglet`,  another error raises:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/36787333/212548242-73d89c8d-0648-43b9-8399-387d173d4f2a.png">

**Comment by araffin** [comment]
See https://stackoverflow.com/questions/74314778/nameerror-name-glpushmatrix-is-not-defined
You need to install pyglet < 2.0, I would welcome a PR that solves that issue =)

```
!pip install pyglet==1.5.27
```
in this case.
