### ISSUE TITLE
getting_started notebook `evaluate_policy`

### ISSUE THREAD

**Issue by luigiannelli** [Stable-Baselines-Team/rl-colab-notebooks#6]
The results of the `evaluate_policy` function given by Stable-Baselines3 and the `evaluate` function defined explicitly in the notebook differ.

**Comment by araffin** [comment]
Hello,
could you elaborate?
Did you make sure to seed the env the same way and use deterministic evaluation?

**Comment by luigiannelli** [comment]
you are right, the problem is the missing `deterministic=True` in the definition of the function `evaluate` in `stable_baselines_getting_started.ipynb`.

thanks.

**Comment by araffin** [comment]
Fixed ;)
